In [1]:
import pandas as pd
import numpy as np

#### Quick look at the data structure

In [2]:
housing = pd.read_csv("housing.csv")

In [3]:
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
longitude             20640 non-null float64
latitude              20640 non-null float64
housing_median_age    20640 non-null float64
total_rooms           20640 non-null float64
total_bedrooms        20433 non-null float64
population            20640 non-null float64
households            20640 non-null float64
median_income         20640 non-null float64
median_house_value    20640 non-null float64
ocean_proximity       20640 non-null object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [5]:
housing["ocean_proximity"].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [6]:
print(housing.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000
mean    -119.569704     35.631861           28.639486   2635.763081
std        2.003532      2.135952           12.585558   2181.615252
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.800000     33.930000           18.000000   1447.750000
50%     -118.490000     34.260000           29.000000   2127.000000
75%     -118.010000     37.710000           37.000000   3148.000000
max     -114.310000     41.950000           52.000000  39320.000000

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000
mean       537.870553   1425.476744    499.539680       3.870671
std        421.385070   1132.462122    382.329753       1.899822
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    787.000000    280.000000       2.563400
50%        435.000000   1166.000000    409.000000       3.534800
75%        647.000000   1725.000000    605.000000       4.743250
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20640.000000
mean        206855.816909
std         115395.615874
min          14999.000000
25%         119600.000000
50%         179700.000000
75%         264725.000000
max         500001.000000

#### Looking for correlation

In [7]:
corr_matrix = housing.corr()
corr_matrix["median_house_value"].sort_values(ascending = False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [8]:
housing["rooms_per_household"] = housing["total_rooms"] / housing["population"]
housing["population_per_household"] = housing["population"] / housing["households"]
corr_matrix = housing.corr()
corr_matrix["median_house_value"].sort_values(ascending=False)

median_house_value          1.000000
median_income               0.688075
rooms_per_household         0.209482
total_rooms                 0.134153
housing_median_age          0.105623
households                  0.065843
total_bedrooms              0.049686
population_per_household   -0.023737
population                 -0.024650
longitude                  -0.045967
latitude                   -0.144160
Name: median_house_value, dtype: float64

#### Prepare the data for Machine Learning algorithms

In [9]:
housing[housing.isnull().any(axis=1)].head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,population_per_household
290,-122.16,37.77,47.0,1256.0,NaN,570.0,218.0,4.3750,161900.0,NEAR BAY,2.203509,2.614679
341,-122.17,37.75,38.0,992.0,NaN,732.0,259.0,1.6196,85100.0,NEAR BAY,1.355191,2.826255
538,-122.28,37.78,29.0,5154.0,NaN,3741.0,1273.0,2.5762,173400.0,NEAR BAY,1.377706,2.938727
563,-122.24,37.75,45.0,891.0,NaN,384.0,146.0,4.9489,247100.0,NEAR BAY,2.320312,2.630137
696,-122.10,37.69,41.0,746.0,NaN,387.0,161.0,3.9063,178400.0,NEAR BAY,1.927649,2.403727
738,-122.14,37.67,37.0,3342.0,NaN,1635.0,557.0,4.7933,186900.0,NEAR BAY,2.044037,2.935368
1097,-121.77,39.66,20.0,3759.0,NaN,1705.0,600.0,4.7120,158600.0,INLAND,2.204692,2.841667
1350,-121.95,38.03,5.0,5526.0,NaN,3207.0,1012.0,4.0767,143100.0,INLAND,1.723106,3.168972
1456,-121.98,37.96,22.0,2987.0,NaN,1420.0,540.0,3.6500,204100.0,INLAND,2.103521,2.629630
1493,-122.01,37.94,23.0,3741.0,NaN,1339.0,499.0,6.7061,322300.0,NEAR BAY,2.793876,2.683367

In [10]:
# housing = housing.dropna(subset=["total_bedrooms"])    # option 1
housing = housing.drop("total_bedrooms", axis=1)       # option 2
# median = housing["total_bedrooms"].median()            # option 3
# housing["total_bedrooms"].fillna(median, inplace=True) # option 3
housing

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,population_per_household
0,-122.23,37.88,41.0,880.0,322.0,126.0,8.3252,452600.0,NEAR BAY,2.732919,2.555556
1,-122.22,37.86,21.0,7099.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,2.956685,2.109842
2,-122.24,37.85,52.0,1467.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2.957661,2.802260
3,-122.25,37.85,52.0,1274.0,558.0,219.0,5.6431,341300.0,NEAR BAY,2.283154,2.547945
4,-122.25,37.85,52.0,1627.0,565.0,259.0,3.8462,342200.0,NEAR BAY,2.879646,2.181467
5,-122.25,37.85,52.0,919.0,413.0,193.0,4.0368,269700.0,NEAR BAY,2.225182,2.139896
6,-122.25,37.84,52.0,2535.0,1094.0,514.0,3.6591,299200.0,NEAR BAY,2.317185,2.128405
7,-122.25,37.84,52.0,3104.0,1157.0,647.0,3.1200,241400.0,NEAR BAY,2.682800,1.788253
8,-122.26,37.84,42.0,2555.0,1206.0,595.0,2.0804,226700.0,NEAR BAY,2.118574,2.026891
9,-122.25,37.84,52.0,3549.0,1551.0,714.0,3.6912,261100.0,NEAR BAY,2.288201,2.172269
10,-122.26,37.85,52.0,2202.0,910.0,402.0,3.2031,281500.0,NEAR BAY,2.419780,2.263682
11,-122.26,37.85,52.0,3503.0,1504.0,734.0,3.2705,241800.0,NEAR BAY,2.329122,2.049046
12,-122.26,37.85,52.0,2491.0,1098.0,468.0,3.0750,213500.0,NEAR BAY,2.268670,2.346154
13,-122.26,37.84,52.0,696.0,345.0,174.0,2.6736,191300.0,NEAR BAY,2.017391,1.982759
14,-122.26,37.85,52.0,2643.0,1212.0,620.0,1.9167,159200.0,NEAR BAY,2.180693,1.954839
15,-122.26,37.85,50.0,1120.0,697.0,264.0,2.1250,140000.0,NEAR BAY,1.606887,2.640152
16,-122.27,37.85,52.0,1966.0,793.0,331.0,2.7750,152500.0,NEAR BAY,2.479193,2.395770
17,-122.27,37.85,52.0,1228.0,648.0,303.0,2.1202,155500.0,NEAR BAY,1.895062,2.138614
18,-122.26,37.84,50.0,2239.0,990.0,419.0,1.9911,158700.0,NEAR BAY,2.261616,2.362768
19,-122.27,37.84,52.0,1503.0,690.0,275.0,2.6033,162900.0,NEAR BAY,2.178261,2.509091
20,-122.27,37.85,40.0,751.0,409.0,166.0,1.3578,147500.0,NEAR BAY,1.836186,2.463855
21,-122.27,37.85,42.0,1639.0,929.0,366.0,1.7135,159800.0,NEAR BAY,1.764263,2.538251
22,-122.27,37.84,52.0,2436.0,1015.0,478.0,1.7250,113900.0,NEAR BAY,2.400000,2.123431
23,-122.27,37.84,52.0,1688.0,853.0,325.0,2.1806,99700.0,NEAR BAY,1.978898,2.624615
24,-122.27,37.84,52.0,2224.0,1006.0,422.0,2.6000,132600.0,NEAR BAY,2.210736,2.383886
25,-122.28,37.85,41.0,535.0,317.0,119.0,2.4038,107500.0,NEAR BAY,1.687697,2.663866
26,-122.28,37.85,49.0,1130.0,607.0,239.0,2.4597,93800.0,NEAR BAY,1.861614,2.539749
27,-122.28,37.85,52.0,1898.0,1102.0,397.0,1.8080,105500.0,NEAR BAY,1.722323,2.775819
28,-122.28,37.84,50.0,2082.0,1131.0,473.0,1.6424,108900.0,NEAR BAY,1.840849,2.391121
29,-122.28,37.84,52.0,729.0,395.0,155.0,1.6875,132000.0,NEAR BAY,1.845570,2.548387
...,...,...,...,...,...,...,...,...,...,...,...
20610,-121.56,39.10,28.0,2130.0,1195.0,439.0,1.3631,45500.0,INLAND,1.782427,2.722096
20611,-121.55,39.10,27.0,1783.0,1163.0,409.0,1.2857,47000.0,INLAND,1.533104,2.843521
20612,-121.56,39.08,26.0,1377.0,761.0,267.0,1.4934,48300.0,INLAND,1.809461,2.850187
20613,-121.55,39.09,31.0,1728.0,1167.0,384.0,1.4958,53400.0,INLAND,1.480720,3.039062
20614,-121.54,39.08,26.0,2276.0,1455.0,474.0,2.4695,58000.0,INLAND,1.564261,3.069620
20615,-121.54,39.08,23.0,1076.0,724.0,197.0,2.3598,57500.0,INLAND,1.486188,3.675127
20616,-121.53,39.08,15.0,1810.0,1157.0,375.0,2.0469,55100.0,INLAND,1.564391,3.085333
20617,-121.53,39.06,20.0,561.0,308.0,114.0,3.3021,70800.0,INLAND,1.821429,2.701754
20618,-121.55,39.06,25.0,1332.0,726.0,226.0,2.2500,63400.0,INLAND,1.834711,3.212389
20619,-121.56,39.01,22.0,1891.0,1023.0,296.0,2.7303,99100.0,INLAND,1.848485,3.456081
20620,-121.48,39.05,40.0,198.0,151.0,48.0,4.5625,100000.0,INLAND,1.311258,3.145833
20621,-121.47,39.01,37.0,1244.0,484.0,157.0,2.3661,77500.0,INLAND,2.570248,3.082803
20622,-121.44,39.00,20.0,755.0,457.0,157.0,2.4167,67000.0,INLAND,1.652079,2.910828
20623,-121.37,39.03,32.0,1158.0,598.0,227.0,2.8235,65500.0,INLAND,1.936455,2.634361
20624,-121.41,39.04,16.0,1698.0,731.0,291.0,3.0739,87200.0,INLAND,2.322845,2.512027
20625,-121.52,39.12,37.0,102.0,29.0,14.0,4.1250,72000.0,INLAND,3.517241,2.071429
20626,-121.43,39.18,36.0,1124.0,504.0,171.0,2.1667,93800.0,INLAND,2.230159,2.947368
20627,-121.32,39.13,5.0,358.0,169.0,59.0,3.0000,162500.0,INLAND,2.118343,2.864407
20628,-121.48,39.10,19.0,2043.0,1018.0,390.0,2.5952,92400.0,INLAND,2.006876,2.610256
20629,-121.39,39.12,28.0,10035.0,6912.0,1818.0,2.0943,108300.0,INLAND,1.451823,3.801980
20630,-121.32,39.29,11.0,2640.0,1257.0,445.0,3.5673,112000.0,INLAND,2.100239,2.824719
20631,-121.40,39.33,15.0,2655.0,1200.0,432.0,3.5179,107200.0,INLAND,2.212500,2.777778
20632,-121.45,39.26,15.0,2319.0,1047.0,385.0,3.1250,115600.0,INLAND,2.214900,2.719481
20633,-121.53,39.19,27.0,2080.0,1082.0,382.0,2.5495,98300.0,INLAND,1.922366,2.832461
20634,-121.56,39.27,28.0,2332.0,1041.0,344.0,3.7125,116800.0,INLAND,2.240154,3.026163
20635,-121.09,39.48,25.0,1665.0,845.0,330.0,1.5603,78100.0,INLAND,1.970414,2.560606
20636,-121.21,39.49,18.0,697.0,356.0,114.0,2.5568,77100.0,INLAND,1.957865,3.122807
20637,-121.22,39.43,17.0,2254.0,1007.0,433.0,1.7000,92300.0,INLAND,2.238332,2.325635
20638,-121.32,39.43,18.0,1860.0,741.0,349.0,1.8672,84700.0,INLAND,2.510121,2.123209
20639,-121.24,39.37,16.0,2785.0,1387.0,530.0,2.3886,89400.0,INLAND,2.007931,2.616981

#### Handling Text and Categorical Attributes

In [11]:
housing_cat = housing[["ocean_proximity"]]
housing_cat.head(10)

  ocean_proximity
0        NEAR BAY
1        NEAR BAY
2        NEAR BAY
3        NEAR BAY
4        NEAR BAY
5        NEAR BAY
6        NEAR BAY
7        NEAR BAY
8        NEAR BAY
9        NEAR BAY

In [12]:
# 分類作法 A

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
housing_cat = housing["ocean_proximity"]
housing_cat_encoded = encoder.fit_transform(housing_cat)
housing_cat_encoded

array([3, 3, 3, ..., 1, 1, 1])

In [13]:
print(encoder.classes_)

['<1H OCEAN' 'INLAND' 'ISLAND' 'NEAR BAY' 'NEAR OCEAN']

In [14]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(categories='auto')
housing_cat_1hot = encoder.fit_transform(housing_cat_encoded.reshape(-1,1))
housing_cat_1hot

<20640x5 sparse matrix of type '<class 'numpy.float64'>'
	with 20640 stored elements in Compressed Sparse Row format>

In [15]:
housing_cat_1hot.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [16]:
# 分類作法 B
from sklearn.preprocessing import LabelBinarizer

encoder = LabelBinarizer()
encoder.fit_transform(housing_cat)

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       ...,
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0]])

#### combine housing and categorical

In [17]:
pd.DataFrame(housing_cat_1hot.toarray()).iloc[:, 1:].head()

     1    2    3    4
0  0.0  0.0  1.0  0.0
1  0.0  0.0  1.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  1.0  0.0
4  0.0  0.0  1.0  0.0

In [18]:
housing_final = pd.concat([housing, pd.DataFrame(housing_cat_1hot.toarray()).iloc[:, 1:]], axis=1)

In [19]:
housing_final.head()

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,population_per_household,1,2,3,4
0,-122.23,37.88,41.0,880.0,322.0,126.0,8.3252,452600.0,NEAR BAY,2.732919,2.555556,0.0,0.0,1.0,0.0
1,-122.22,37.86,21.0,7099.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,2.956685,2.109842,0.0,0.0,1.0,0.0
2,-122.24,37.85,52.0,1467.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2.957661,2.802260,0.0,0.0,1.0,0.0
3,-122.25,37.85,52.0,1274.0,558.0,219.0,5.6431,341300.0,NEAR BAY,2.283154,2.547945,0.0,0.0,1.0,0.0
4,-122.25,37.85,52.0,1627.0,565.0,259.0,3.8462,342200.0,NEAR BAY,2.879646,2.181467,0.0,0.0,1.0,0.0

# Prepare the data for Machine Learning algorithms

In [20]:
X = housing_final.drop("median_house_value", axis=1).drop("ocean_proximity", axis=1)
X.head()

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,rooms_per_household,population_per_household,1,2,3,4
0,-122.23,37.88,41.0,880.0,322.0,126.0,8.3252,2.732919,2.555556,0.0,0.0,1.0,0.0
1,-122.22,37.86,21.0,7099.0,2401.0,1138.0,8.3014,2.956685,2.109842,0.0,0.0,1.0,0.0
2,-122.24,37.85,52.0,1467.0,496.0,177.0,7.2574,2.957661,2.802260,0.0,0.0,1.0,0.0
3,-122.25,37.85,52.0,1274.0,558.0,219.0,5.6431,2.283154,2.547945,0.0,0.0,1.0,0.0
4,-122.25,37.85,52.0,1627.0,565.0,259.0,3.8462,2.879646,2.181467,0.0,0.0,1.0,0.0

In [21]:
y = housing_final[["median_house_value"]]
y.head()

   median_house_value
0            452600.0
1            358500.0
2            352100.0
3            341300.0
4            342200.0

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [23]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
# sc_X.fit_transform(X_train["longitude"])

In [24]:
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,rooms_per_household,population_per_household,1,2,3,4
12069,-117.55,33.83,6.0,502.0,228.0,65.0,4.2386,2.201754,3.507692,1.0,0.0,0.0,0.0
15925,-122.44,37.73,52.0,2381.0,1485.0,447.0,4.3898,1.603367,3.322148,0.0,0.0,1.0,0.0
11162,-118.00,33.83,26.0,1718.0,1022.0,368.0,3.9333,1.681018,2.777174,0.0,0.0,0.0,0.0
4904,-118.26,34.01,38.0,697.0,749.0,206.0,1.4653,0.930574,3.635922,0.0,0.0,0.0,0.0
4683,-118.36,34.08,52.0,2373.0,1135.0,576.0,3.1765,2.090749,1.970486,0.0,0.0,0.0,0.0

In [25]:
X_train[['longitude', 'latitude']] = sc_X.fit_transform(X_train[['longitude', 'latitude']])

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\pandas\core\frame.py:3385: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.loc._setitem_with_indexer((slice(None), indexer), value)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\pandas\core\frame.py:3357: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_array(key, value)

In [26]:
X_train.head()

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,rooms_per_household,population_per_household,1,2,3,4
12069,1.003899,-0.840062,6.0,502.0,228.0,65.0,4.2386,2.201754,3.507692,1.0,0.0,0.0,0.0
15925,-1.434772,0.985364,52.0,2381.0,1485.0,447.0,4.3898,1.603367,3.322148,0.0,0.0,1.0,0.0
11162,0.779481,-0.840062,26.0,1718.0,1022.0,368.0,3.9333,1.681018,2.777174,0.0,0.0,0.0,0.0
4904,0.649818,-0.755812,38.0,697.0,749.0,206.0,1.4653,0.930574,3.635922,0.0,0.0,0.0,0.0
4683,0.599947,-0.723048,52.0,2373.0,1135.0,576.0,3.1765,2.090749,1.970486,0.0,0.0,0.0,0.0

In [27]:
# # Feature Scaling
# from sklearn.preprocessing import StandardScaler
# sc_X = StandardScaler()
# X_train = sc_X.fit_transform(X_train)
# X_test = sc_X.transform(X_test)
# sc_y = StandardScaler()
# y_train = sc_y.fit_transform(y_train)

In [28]:
type(y_train)

pandas.core.frame.DataFrame

In [29]:
type(X_train)

pandas.core.frame.DataFrame

#### null detection

In [30]:
# 方法 A
# y_train.isnull().any(axis=1)
# X_train.isnull().any(axis=1)

# 方法 B
# np.isnan(y_train).any()
# np.isnan(X_train).any()

# Prepare the data for Machine Learning algorithms

In [31]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [32]:
# lin_reg.predict(X_train)
# lin_reg.predict(X_test)

#### 檢驗 train set 績效

In [33]:
from sklearn.metrics import mean_squared_error

housing_predictions = lin_reg.predict(X_train)
lin_mse = mean_squared_error(y_train, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_train, housing_predictions)
print(lin_mae)

67973.296447151
49461.47745791734

#### 檢驗 test set 績效

In [34]:
from sklearn.metrics import mean_squared_error

housing_predictions = lin_reg.predict(X_test)
lin_mse = mean_squared_error(y_test, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_test, housing_predictions)
print(lin_mae)

4959090.752593165
4958542.753708021

#### 模型換決策樹

In [35]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor()
tree_reg.fit(X_train, y_train)
# housing_predictions = tree_reg.predict(housing_prepared)
# tree_mse = mean_squared_error(housing_labels, housing_predictions)
# tree_rmse = np.sqrt(tree_mse)
# tree_rmse

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

#### 檢驗 train set的績效

In [36]:
from sklearn.metrics import mean_squared_error

housing_predictions = tree_reg.predict(X_train)
lin_mse = mean_squared_error(y_train, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_train, housing_predictions)
print(lin_mae)

0.0
0.0

#### 檢驗 test set 績效

In [37]:
from sklearn.metrics import mean_squared_error

housing_predictions = tree_reg.predict(X_test)
lin_mse = mean_squared_error(y_test, housing_predictions)
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

from sklearn.metrics import mean_absolute_error
lin_mae = mean_absolute_error(y_test, housing_predictions)
print(lin_mae)

104619.45193577094
77397.00872093023

# Fine-tune your model

In [38]:
from sklearn.model_selection import cross_val_score

tree_scores = cross_val_score(tree_reg, X_train, y_train,
                              scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-tree_scores)

In [39]:
tree_rmse_scores

array([72335.84644414, 66531.5096737 , 67215.96709583, 70624.33104016,
       75960.69587806, 71984.95620928, 67601.53370637, 69785.89566985,
       71205.31211877, 64093.02656629])

In [40]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())

display_scores(tree_rmse_scores)

Scores: [72335.84644414 66531.5096737  67215.96709583 70624.33104016
 75960.69587806 71984.95620928 67601.53370637 69785.89566985
 71205.31211877 64093.02656629]
Mean: 69733.90744024396
Standard deviation: 3263.935046679895

In [41]:
lin_scores = cross_val_score(lin_reg, X_train, y_train,
                             scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores: [68945.97646887 65590.9449141  69121.65720735 67253.67505489
 72308.16414768 67532.58484636 66712.83282223 68798.4654893
 71303.52108226 64654.42581677]
Mean: 68222.22478498144
Standard deviation: 2262.717725152657

In [42]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor()
forest_reg.fit(X_train, y_train)
housing_predictions = forest_reg.predict(X_train)
forest_mse = mean_squared_error(y_train, housing_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

21878.918340631742

In [43]:
from sklearn.model_selection import cross_val_score

forest_scores = cross_val_score(forest_reg, X_train, y_train,
                                scoring="neg_mean_squared_error", cv=10)
forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

Scores: [54025.80375175 52084.19205839 50539.89955877 50556.53140251
 54385.24129767 52793.65595638 51680.45864828 50969.78891397
 53832.60772781 47248.98860783]
Mean: 51811.716792335654
Standard deviation: 2034.3359134077882

In [44]:
scores = cross_val_score(lin_reg, X_train, y_train, scoring="neg_mean_squared_error", cv=10)
pd.Series(np.sqrt(-scores)).describe()

count       10.000000
mean     68222.224785
std       2385.113905
min      64654.425817
25%      66848.043380
50%      68165.525168
75%      69077.737023
max      72308.164148
dtype: float64

In [45]:
from sklearn.svm import SVR

svm_reg = SVR(kernel="linear")
svm_reg.fit(X_train, y_train)
housing_predictions = svm_reg.predict(X_train)
svm_mse = mean_squared_error(y_train, housing_predictions)
svm_rmse = np.sqrt(svm_mse)
svm_rmse

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

94179.55824305126

In [46]:
from sklearn.model_selection import GridSearchCV

param_grid = [
        {'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]},
        {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
    ]

forest_reg = RandomForestRegressor()
grid_search = GridSearchCV(forest_reg, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_search.py:740: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid=[{'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]}, {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_squared_error', verbose=0)

In [47]:
grid_search.best_params_

{'max_features': 6, 'n_estimators': 30}

In [48]:
grid_search.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=6, max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=30, n_jobs=None, oob_score=False,
           random_state=None, verbose=0, warm_start=False)

In [49]:
cvres = grid_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

62132.49333373266 {'max_features': 2, 'n_estimators': 3}
53673.28817068045 {'max_features': 2, 'n_estimators': 10}
51163.25314837313 {'max_features': 2, 'n_estimators': 30}
59117.31165692548 {'max_features': 4, 'n_estimators': 3}
51598.55043785641 {'max_features': 4, 'n_estimators': 10}
49703.8637595398 {'max_features': 4, 'n_estimators': 30}
57541.7648832333 {'max_features': 6, 'n_estimators': 3}
51381.04090769564 {'max_features': 6, 'n_estimators': 10}
49617.696663810944 {'max_features': 6, 'n_estimators': 30}
57084.629945210385 {'max_features': 8, 'n_estimators': 3}
51483.665757421615 {'max_features': 8, 'n_estimators': 10}
49705.8307026469 {'max_features': 8, 'n_estimators': 30}
59905.58286198555 {'bootstrap': False, 'max_features': 2, 'n_estimators': 3}
52731.73827812246 {'bootstrap': False, 'max_features': 2, 'n_estimators': 10}
59326.817912934726 {'bootstrap': False, 'max_features': 3, 'n_estimators': 3}
51090.37617572541 {'bootstrap': False, 'max_features': 3, 'n_estimators': 10}
57738.26535634694 {'bootstrap': False, 'max_features': 4, 'n_estimators': 3}
50396.800355940955 {'bootstrap': False, 'max_features': 4, 'n_estimators': 10}

In [50]:
pd.DataFrame(grid_search.cv_results_)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split3_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('split4_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\utils\deprecation.py:125: FutureWarning: You are accessing a training score ('std_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_features,param_n_estimators,param_bootstrap,params,split0_test_score,split1_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.073215,0.009016,0.004784,0.000746,2,3,NaN,"{'max_features': 2, 'n_estimators': 3}",-3.879755e+09,-3.698058e+09,...,-3.860447e+09,8.458315e+07,18,-1.025773e+09,-1.030998e+09,-9.655254e+08,-1.035566e+09,-9.868096e+08,-1.008934e+09,2.776124e+07
1,0.227392,0.007588,0.011367,0.001621,2,10,NaN,"{'max_features': 2, 'n_estimators': 10}",-2.841365e+09,-2.827420e+09,...,-2.880822e+09,1.510741e+08,11,-5.605812e+08,-5.464350e+08,-5.601360e+08,-5.348855e+08,-5.893159e+08,-5.582707e+08,1.821853e+07
2,0.575661,0.022214,0.028527,0.003811,2,30,NaN,"{'max_features': 2, 'n_estimators': 30}",-2.696419e+09,-2.509175e+09,...,-2.617678e+09,9.411336e+07,6,-4.107305e+08,-4.174434e+08,-3.945974e+08,-4.120486e+08,-4.051748e+08,-4.079989e+08,7.754161e+06
3,0.095946,0.001724,0.004580,0.000498,4,3,NaN,"{'max_features': 4, 'n_estimators': 3}",-3.577140e+09,-3.416306e+09,...,-3.494857e+09,8.652360e+07,15,-8.889811e+08,-9.195542e+08,-8.779847e+08,-9.396710e+08,-9.283045e+08,-9.108991e+08,2.353481e+07
4,0.340094,0.016158,0.011374,0.001467,4,10,NaN,"{'max_features': 4, 'n_estimators': 10}",-2.749393e+09,-2.545233e+09,...,-2.662410e+09,9.623256e+07,9,-4.952528e+08,-5.042590e+08,-4.764279e+08,-5.033830e+08,-5.115125e+08,-4.981670e+08,1.202915e+07
5,1.010508,0.031433,0.028531,0.001360,4,30,NaN,"{'max_features': 4, 'n_estimators': 30}",-2.488962e+09,-2.356410e+09,...,-2.470474e+09,9.357350e+07,2,-3.664113e+08,-3.825157e+08,-3.654025e+08,-3.852482e+08,-3.884179e+08,-3.775991e+08,9.732960e+06
6,0.155793,0.015644,0.005586,0.001013,6,3,NaN,"{'max_features': 6, 'n_estimators': 3}",-3.497132e+09,-3.161511e+09,...,-3.311055e+09,1.461500e+08,13,-8.766944e+08,-9.033346e+08,-8.740250e+08,-9.234308e+08,-8.473666e+08,-8.849703e+08,2.614872e+07
7,0.473469,0.023415,0.010574,0.000507,6,10,NaN,"{'max_features': 6, 'n_estimators': 10}",-2.675145e+09,-2.535441e+09,...,-2.640011e+09,1.291399e+08,7,-4.618397e+08,-4.838890e+08,-4.874215e+08,-4.940466e+08,-4.803099e+08,-4.815014e+08,1.082711e+07
8,1.363557,0.014165,0.030039,0.001014,6,30,NaN,"{'max_features': 6, 'n_estimators': 30}",-2.547315e+09,-2.386750e+09,...,-2.461916e+09,8.079176e+07,1,-3.627905e+08,-3.681510e+08,-3.671080e+08,-3.800281e+08,-3.825687e+08,-3.721292e+08,7.741135e+06
9,0.182224,0.010898,0.004992,0.001102,8,3,NaN,"{'max_features': 8, 'n_estimators': 3}",-3.417063e+09,-3.192742e+09,...,-3.258655e+09,1.655176e+08,12,-8.639131e+08,-8.613334e+08,-8.438903e+08,-8.616387e+08,-8.228592e+08,-8.507269e+08,1.567665e+07
10,0.597022,0.024271,0.011582,0.001339,8,10,NaN,"{'max_features': 8, 'n_estimators': 10}",-2.797321e+09,-2.557522e+09,...,-2.650568e+09,1.233280e+08,8,-4.701929e+08,-5.047001e+08,-4.988509e+08,-4.717630e+08,-4.815761e+08,-4.854166e+08,1.403754e+07
11,1.770474,0.072640,0.030454,0.002797,8,30,NaN,"{'max_features': 8, 'n_estimators': 30}",-2.595093e+09,-2.356780e+09,...,-2.470670e+09,9.376854e+07,3,-3.673668e+08,-3.840702e+08,-3.585707e+08,-3.810144e+08,-3.771662e+08,-3.736377e+08,9.402552e+06
12,0.092906,0.003686,0.005188,0.000739,2,3,False,"{'bootstrap': False, 'max_features': 2, 'n_est...",-3.799684e+09,-3.520606e+09,...,-3.588679e+09,2.057824e+08,17,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00
13,0.305021,0.001121,0.012165,0.000969,2,10,False,"{'bootstrap': False, 'max_features': 2, 'n_est...",-2.874914e+09,-2.624751e+09,...,-2.780636e+09,1.551952e+08,10,-1.048285e+03,-0.000000e+00,-0.000000e+00,-7.327782e+00,-1.456472e+01,-2.140356e+02,4.171599e+02
14,0.124356,0.002130,0.004784,0.000384,3,3,False,"{'bootstrap': False, 'max_features': 3, 'n_est...",-3.879532e+09,-3.315265e+09,...,-3.519671e+09,1.991171e+08,16,-8.243538e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-1.648708e+00,3.297415e+00
15,0.425791,0.019624,0.012185,0.000717,3,10,False,"{'bootstrap': False, 'max_features': 3, 'n_est...",-2.737810e+09,-2.485662e+09,...,-2.610227e+09,1.036246e+08,5,-0.000000e+00,-1.514119e-02,-0.000000e+00,-0.000000e+00,-0.000000e+00,-3.028238e-03,6.056477e-03
16,0.155977,0.001533,0.005281,0.000388,4,3,False,"{'bootstrap': False, 'max_features': 4, 'n_est...",-3.401451e+09,-3.242414e+09,...,-3.333707e+09,1.605650e+08,14,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,-0.000000e+00,0.000000e+00,0.000000e+00
17,0.529246,0.026676,0.012558,0.001182,4,10,False,"{'bootstrap': False, 'max_features': 4, 'n_est...",-2.667869e+09,-2.347635e+09,...,-2.539837e+09,1.362322e+08,4,-0.000000e+00,-0.000000e+00,-0.000000e+00,-3.785011e-01,-0.000000e+00,-7.570023e-02,1.514005e-01

In [51]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs = {
        'n_estimators': randint(low=1, high=200),
        'max_features': randint(low=1, high=8),
    }

forest_reg = RandomForestRegressor()
rnd_search = RandomizedSearchCV(forest_reg, param_distributions=param_distribs,
                                n_iter=10, cv=5, scoring='neg_mean_squared_error')
rnd_search.fit(X_train, y_train)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_validation.py:528: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\USER\Anaconda3\envs\deep\lib\site-packages\sklearn\model_selection\_search.py:740: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
          estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
          fit_params=None, iid='warn', n_iter=10, n_jobs=None,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000025428AA8080>, 'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000025428AA8048>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring='neg_mean_squared_error',
          verbose=0)

In [52]:
cvres = rnd_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(np.sqrt(-mean_score), params)

48679.215715103965 {'max_features': 6, 'n_estimators': 77}
48467.49482652831 {'max_features': 5, 'n_estimators': 114}
48806.4498689856 {'max_features': 4, 'n_estimators': 97}
49763.58404289101 {'max_features': 3, 'n_estimators': 47}
61715.84186643642 {'max_features': 2, 'n_estimators': 3}
48663.014212662056 {'max_features': 4, 'n_estimators': 117}
48618.298696338425 {'max_features': 6, 'n_estimators': 130}
54126.15710799759 {'max_features': 1, 'n_estimators': 26}
49006.59497997398 {'max_features': 3, 'n_estimators': 171}
48680.58310950676 {'max_features': 4, 'n_estimators': 187}

In [53]:
feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances

array([7.40328041e-02, 7.41099774e-02, 4.30277253e-02, 2.07420631e-02,
       1.87980285e-02, 2.09756739e-02, 4.08419559e-01, 9.96078809e-02,
       8.38964356e-02, 1.49446950e-01, 1.34646676e-04, 2.78596324e-03,
       4.02229227e-03])